### ISSUE TITLE
Web API for integration with hMAS vocabularies

### ISSUE THREAD

**Issue by danaivach** [Interactions-HSG/yggdrasil#20]
Below is the suggested Web API. See [here for information on the mentioned special triples](#special-triples).

- **GET `<root>`** 
Returns the resource profile of the Hypermedia MAS Platform. The resource profile exposes the following Signifiers:
  - Create Workspace
- **POST `<*/workspaces/>` (Create Workspace)**
Returns the resource profile of the created Workspace. The response headers `Location` and `Content-Location` point to the location of the Workspace `<*/workspaces/:wkspid>`. A _host triple_ is added to the resource profile of the Platform (and the resource profile of the created Workspace). If the created Workspace is a sub-workspace,  a _containment triple_ is added to the resource profile of the parent Workspace (and the resource profile of the created Workspace). If the created Workspace is a sub-workspace and its parent workspace (Parent 0) is a sub-workspace,  a _transitive containment triple_ is added to the resource profiles of _all_ parent workspaces that can be tracked from Parent 0 to the root Parent through a containment triple (and the resource profile of the created Workspace). The resource profile exposes the following Signifiers:
  - Join Workspace
  - Quit Workspace
  - Add Artifact
  - Remove Artifact
  - Create Workspace 
- **POST `<*/workspaces/:wkspid>` (Join Workspace); Request header field `X-Agent-WebID`: the URI of the Agent** 
Returns the resource profile of the created body Artifact. The response headers `Location` and `Content-Location` point to the location of the Artifact `<*/workspaces/:wkspid/artifacts/:artid>`. A _host triple_ is added to the resource profile of the Platform (and the resource profile of the Artifact). A _containment triple_ is added to the resource profile of the Workspace (and the resource profile of the Artifact). If the Workspace is a sub-workspace, then a _transitive containment triple_ is added to the resource profiles of _all_ parent workspaces that have a containment triple or a transitive containment triple with the Workspace (and the resource profile of the Artifact). The URI of the Agent (provided in `X-Agent-WebID`) is dereferenced to retrieve the Resource Profile of the Agent (located at `<*/agents/:agentid>`). An _embodiment triple_ is added to the resource profile of the Agent (and the resource profile of the Artifact).  
- **POST `<*/workspaces/:wkspid/artifacts/>` (Add Artifact); Payload: the Resource Profile of an Artifact** 
Returns the resource profile of the registered Artifact. The response headers "Location" and "Content-Location" point to the location of the Artifact `<*/workspaces/:wkspid/artifacts/:artId>`.  A _host triple_ is added to the resource profile of the Platform (and the resource profile of the Artifact). A _containment triple_ is added to the resource profile of the Workspace (and the resource profile of the Artifact). If the Workspace is a sub-workspace, then a _transitive containment triple_ is added to the resource profiles of _all_ parent workspaces that have a containment triple or a transitive containment triple with the Workspace (and the resource profile of the Artifact). 
- **DELETE `<*/workspaces/artifacts/:artId>` (Quit Workspace & Remove Artifact)**
Deletes the resource profile of the Artifact. Host triples, containment triples, transitive containment triples, and embodiment triples that relate to the Artifact are removed.
- **GET `<*/workspaces/:wkspid>`**
Returns the resource profile of a Workspace
- **GET `<*/workspaces/:wkspid/artifacts/:artid>`**
Returns the resource profile of an Artifact
- **GET `<*/agents/:agentid>`**
Returns the resource profile of an Agent

### Special Triples<a href="#special-triples" id="special-triples"/>
- **host triple**: Adding a host triple between a Platform `<root#platform>` and a resource `<*/:rscid#rsc>`, should result to the addition of the following:
  - `<root#platform> <https://purl.org/hmas/core#hosts> <*/:rscid#rsc>`
  - `<*/:rscid#rsc> <https://purl.org/hmas/core#isHostedOn> <root#platform>`
- **containment triple**: Adding a containment triple between a Workspace `<*/workspaces/:wkspid>` and a resource `<*/:rscid#rsc>`, should result to the addition of the following: 
  -  `<*/workspaces/:wkspid> <https://purl.org/hmas/core#contains> <*/:rscid#rsc>`
  -  `<*/:rscid#rsc> <https://purl.org/hmas/core#isContaintedIn> <*/workspaces/:wkspid>`
- **transitive containment triple**: Adding a transitive containment triple between a Workspace `<*/workspaces/:wkspid>` and a resource `<*/:rscid#rsc>`, should result to the addition of the following: 
  -  `<*/workspaces/:wkspid> <https://purl.org/hmas/core#transitivelyContains> <*/:rscid#rsc>`
  -  `<*/:rscid#rsc> <https://purl.org/hmas/core#isTransitivelyContainedIn> <*/workspaces/:wkspid>`
- **embodiment triple**: Adding an embodiment triple between an Agent `<*/agents/:agentid#agent>` and an Artifact `<*/workspaces/:wkspid/artifacts/:artid#artifact>`, should result to the addition of the following: 
  -  `<*/agents/:agentid#agent> <https://purl.org/hmas/core#hasBody> <*/workspaces/:wkspid/artifacts/:artid#artifact>`
  -  `<*/workspaces/:wkspid/artifacts/:artid#artifact> <https://purl.org/hmas/core#isBodyOf> <*/agents/:agentid#agent>`

**Comment by cake-lier** [comment]
Me and @andreiciortea were discussing about a proposed change for the artifacts API changing it from "/workspaces/:wkspid/artifacts/:artid" to simply "/artifacts/:artid".

Also, in this proposal the "focus" and "stopFocus" operations are missing. Should them be represented?

**Comment by danaivach** [comment]
Hi @cake-lier. Some people are pro non-opaque URIs for facilitating readability by human users. Personally, I see no ontological issue with opaque URIs, and I'm open to transitioning to "/artifacts/:artid" for simplicity, as long as the following are clarified:
- Does "/artifacts/:artid" refer to the URL of an artifact resource, or (also) the endpoint of workspace resources for registering aritfacts contained in said workspaces? In case of only the former, ok. In case that the latter applies: How will information for producing containment triples be provided by the user, e.g. through a containment triple in the submitted artifact profile as part of the payload, through a custom header, etc.?
- Will the "Slug" header continue to be used for naming the artifacts and creating the URLs of the registered artifacts? If yes, will Yggdrasil prohibit the registration of an artifact with a Slug, when an artifact with the same Slug has already been registered? Do you consider that it makes sense from a user perspective that no two artifacts are registered with the same Slug headers even if they are registered in completely different workspaces?

**Comment by cake-lier** [comment]
Hello @danaivach, these are all great questions, which I don't have all the answers to and will need more in-depth discussion with the help of @andreiciortea. 

* If I recall correctly, the idea was to change the URL and the endpoint for registering workspace resources. When the turtle representation is given while bypassing CArtAgo, the workspace name can be found as a triple in the turtle representation. When using a CArtAgO handler, some parameters in a JSON object are passed. In this case, it could be one of the said parameters. 
* The slug header will still be used, and Yggdrasil should prohibit two artifacts with the same name in the same workspace but never prohibit two artifacts with the same name in two different workspaces. But I have no idea how to solve this problem on the Rdf Store-knowledge graph side.
* Currently, we have no body artifacts, and the only operation that exists, "focus," is offered by the workspace.
