### ISSUE TITLE
Format for Web IDs is too restrictive

### ISSUE THREAD

**Issue by cake-lier** [Interactions-HSG/yggdrasil#40]
### Context

Currently, Web IDs supported by the Yggdrasil platform can only follow the format "http(s)://host:platform/agents/agentName."

### Proposed change

Change the format for Web IDs to allow any URIs compliant with the Web ID standard. The original motivation for restricting their format was to enable the extraction of the agent name from its Web ID when joining or leaving a workspace and to notify the correct topic when the agent acts. But when issue #39 gets implemented, the agent name can be directly extracted from the resource URI upon joining a workspace, and the association between the URI and the agent name can be saved in a map. Then, the map can be used for such a scope anytime the name is needed.

### Pros

* The Yggdrasil platform becomes fully compliant with the Web ID standard.
* The future support for authentication based on SOLID OIDC (issue #41) becomes easier.

### Cons

* None at the time of writing.

**Comment by KaiTries** [comment]
Should be resolved. 
There is no restriction anymore on the x-Agent-WebID since the name gets extracted from a different header.

**Comment by danaivach** [comment]
I'm closing this as the issue has been addressed with the latest merge (https://github.com/Interactions-HSG/yggdrasil/pull/50)
