### ISSUE TITLE
Refactor representation factory to make it independent from wot-td-java

### ISSUE THREAD

**Issue by cake-lier** [Interactions-HSG/yggdrasil#43]
## Context

Currently, the RepresentationFactory entity encapsulates all the logic for generating all the different representations: Artifacts, Workspaces, Bodies, Platforms, ...

### Proposed change

The class interface depends on the "wot-td-java" library, but it should be agnostic from its implementation. Also, it should encapsulate fully the logic for validating the input parameters when they are given upon acting on an artifact.

### Pros

* The dependence on wot-td-java would not affect design decisions, being relegated to the implementation and not the interface.
* The switching between wot-td-java and other libraries (like hmas-java) would be easier.

### Cons

* Some types that wot-td-java has are not present elsewhere unless they get encapsulated using some strategy like micro-types, which implies creating ad-hoc types just wrapping those, adding overhead to the Yggdrasil implementation.
* Otherwise, the code using the features only present in wot-td-java can be refactored not to use them, losing some (potentially?) functional features.

**Comment by KaiTries** [comment]
Should be resolved through my pull request.
Utilizing a FactoryFactory we can decide what ontology specific representationfactory should be used. The ontologies are decoupled from the application through a shared interface.
