### ISSUE TITLE
Incorrect platform and workspace URIs in "host" triples

### ISSUE THREAD

**Issue by danaivach** [Interactions-HSG/yggdrasil#46]
Upon creating a resource profile of a Workspace, a "host" triple is added in the profile, like the following:
```
<http://172.27.52.55:8000//workspaces/cup-production> hmas:isHostedOn <http://172.27.52.55:8000//> .
```

Both the workspace and platform URIs have an extra "/" which should be removed.

**Comment by cake-lier** [comment]
I tried to generate a workspace resource profile but couldn't reproduce your error. The generated triple is fine. Are you sure you have correctly specified the "conf.json" configuration file?

**Comment by danaivach** [comment]
I'm closing this as the issue has been addressed with the latest merge (https://github.com/Interactions-HSG/yggdrasil/pull/50)
