### ISSUE TITLE
Refactoring of the environment representation in configuration files

### ISSUE THREAD

**Issue by KaiTries** [Interactions-HSG/yggdrasil#56]
Due to the increased complexity of the system and recent additions such as being able to add metadata to cartago entities through the config files, highlighted a need to refacted the environment representation.

The main bottleneck is that the agent is currently split into two. He is for one mentioned in the artifact in the focused-by parameter and then as well in the workspace itself in the agents array. 

````json

{
  "environment-config" : {
    "workspaces" : [
      {
        "name" : "w1"
        "artifacts" : [
          {
            "name" : "c0",
            "class" : "http://example.org/Counter",
            "init-params" : [
              5
            ],
            "focused-by" : [
              {
                "agent-uri" : "http://localhost:8080/agents/test",
                "callback-uri" : "http://localhost:8081/"
              }
            ]
          }
        ],
        "agents" : [
          "http://localhost:8080/agents/test"
        ]
      }
    ]
  }
}
````

As a first improvement on my main branch I have refactored the agent into one single json object that sits in the workspace as well:

````json
{
  "environment-config" : {
    "workspaces" : [
      {
        "name" : "w1",
        "metadata" : "src/main/resources/w1_test_metadata.ttl",
        "artifacts" : [
          {
            "name" : "c1",
            "class" : "http://example.org/Counter",
            "metadata" : "src/main/resources/c1_test_metadata.ttl"
          }
        ],
        "agents" : [
          {
            "name" : "test_agent",
            "agent-uri" : "http://localhost:8081",
            "callback-uri" : "http://localhost:8081/callback",
            "focused-artifacts" : [
              "c1"
            ],
            "metadata" : "src/main/resources/a1_test_metadata.ttl"
          }
        ]
      }
    ]
  }
}
````

This already makes it much easier to write and read since everything is clearly separated and everything concerning agents is in one place. 

## Possible ways to improve this

While the above proposed change works well and is easy to handle when there are few workspaces or each agent is only present in one workspace, if a configuration would specify multiple workspaces where agents are present in any number of them, there would be a lot of duplication, since agents are still defined in the workspace themselves!

### Make the Agents top-level in the environment

A solution would be to take the agents out of the workspaces. Since the agent-uri, callback-uri anf name would always be the same there is no need to rewrite it in every workspace where they are present. 

Pulling the agent out of the workspace does make it a bit more complicated in how we want to represent the relations between the agent and the environment. How do we now specify in which workspace an agent is present and what artifacts he is focused on (Especially because artifact names are not unique between workspaces and an agent must be present in the given workspace to focus on an artifact )? 

#### 1st approach
This approach would define agents on the top-level and then use the agent-name as a reference in the workspace and artifact.
Pros of this approach are its pretty straight forward and also quite logical on a semantical level. The drawback here is, that the agent is once again split up a bit (but negligible since they are just references).

````json
{
  "environment-config" : {
    "workspaces" : [
      {
        "name" : "w1",
        "agents" : [
          "test_agent"
        ],
        "artifacts" : [
          {
            "name" : "c1",
            "class" : "http://example.org/Counter",
            "focused-by" : [
              "test_agent"
            ]
          }
        ]
      }
    ],
    "agents" : [
      {
        "name" : "test_agent",
        "agent-uri" : "http://localhost:8081",
        "callback-uri" : "http://localhost:8081/callback"
      }
    ]
  }
}

````

#### 2nd approach

In the second approach, instead of defining what agents are in the workspace in the workspace. We have an additional parameter for the agent. The bodies parameter would allow us to have more fine grained control over each body representation. This could be extended to have specific metadata for each body as well as also putting the focusing-on parameter in there as well. The pros here are the customizability and additional control, the drawbacks are increased complexity.

````json
{
  "environment-config" : {
    "workspaces" : [
      {
        "name" : "w1",
        "artifacts" : [
          {
            "name" : "c1",
            "class" : "http://example.org/Counter",
            "focused-by" : [
              "name_one"
            ]
          }
        ]
      }
    ],
    "agents" : [
      {
        "name" : "test_agent",
        "agent-uri" : "http://localhost:8081",
        "callback-uri" : "http://localhost:8081/callback",
        "bodies" : [
          {
            "name" : "name_one",
            "in" : ["w0", "w1"]
          }
        ]
      }
    ]
  }
}
````

**Comment by andreiciortea** [comment]
Thanks, @KaiTries, for the detailed proposal.

Both improvement proposals would work, but I would be inclined towards the 2nd approach — i.e., having an explicit representation of bodies, including what artifacts an agent focuses on in each workspace. My reasoning:
- this would streamline the specification of workspaces, which should help as environments become more complex
- intuitively, it should also be easier to manage more complex environments if the information about the embodiment of an agent is grouped under the agent's definition
- to some extent, this would be closer to JaCaMo project file definitions, which specify what artifacts an agent focuses on as part of an agent's definition
  - just to note: in the current version of JaCaMo, workspace definitions include what agents are located in the workspace, but this would be redundant if we have an explicit representation of bodies
 - an explicit representation of bodies might be useful for adding new features, e.g. adding metadata to agent bodies

I also suggest to move the agent definitions one level above, outside the environment specification, so smthg like:

```json
{
  "agents" : [
    ...
  ],
  "environment-config" : {
    ...
  }
}
```

The reasoning here would be to maintain orthogonality between the agent and environment dimensions. This would be useful as soon as we consider other dimensions that need to reference the agent definitions (e.g., specifications of organizations or interaction protocols).

**Comment by KaiTries** [comment]
hi @andreiciortea, thanks for the input!

Option two would definitely be more robust and extensible in the long run, but adds some additional complexity upfront and some additional design choices still need to be made.

- We need to decide on what is represented in the top-level representation of the agent and what will be put into other objects. 
    ```json
  "agents" :  [
    {
      "name" : "test_agent",
      "agent-uri" : "http://localhost:8081",
      "callback-uri" : "http://localhost:8081/callback",
      "bodies" : [
        {
          "name" : "optional",
          "metadata" : "optional",
        }
      ]
    }
  ],
    ``` 
- I think the **name**, **agent-uri** and **callback-uri** should be obligatory fields that are placed in the top-level representation of the agent. Since these will not change throughout the lifetime of the node.  
- Bodies should be the only additional field that is present at the top-level and links the Agent to his different bodies that may be present in workspaces. 

- Joining and Focusing are the two interactions that need to be represented to enable the full integration of the agents.
    - **Focusing** I think you @andreiciortea mentioned from an environment architects standpoint the focusing is intuitively nested in the artifact that will be focused on. So if we add it to the artifact, the only design choice we need to make is what identifier is used for the focusing, e.g. do we use the Agent name or the Body name. Imo the agent name probably makes the most sense, because for the focusing action we do not need any additional information than the top-level one (uris). But to focus on an artifact the agent needs to join the specific workspace. So therefore a check needs to happen if there is a body present! So using the body name would make that check easier. 
    - **Joining** The information on what body is present in which workspace, naturally falls into two places. Either in the _bodies_ field of the agent where we can specify which bodies are in which workspace, or the inverse in the workspaces as a _joinedby_ field that lists all body names that are joined. 

These decisions are very much design choices and will just change the parsing a bit, but are nonetheless very important to create a nice user experience, that feels intuitive and easy.


The below is an example configuration, with the proposed change. Feel free to add / change this config until we are happy with the config configurations :D (irrelevant info is omitted)
```json
{
  "http-config" : {
    ...
  },
  "notification-config" : {
    ... 
  },
  "agents" :  [
    {
      "name" : "test_agent", // unique identifier for each agent
      "agent-uri" : "http://localhost:8081", // URI of the agents WebID
      "callback-uri" : "http://localhost:8081/callback", // Endpoint for callbacks
      "bodies" : [ // list of body objects
        {
          "name" : "body_one", // unique body name per workspace
          "metadata" : "src/main/resources/a1_body_metadata.ttl", // optional metadata for the specific body representation
          "in" : [ // list of workspaces the body is in - also possible in workspace themselves
            "w1", 
          ]
        }
      ]
    }
  ],
  "environment-config" : {
    "workspaces" : [
      {
        "name" : "w1",
        "metadata" : "src/main/resources/w1_test_metadata.ttl",
        "artifacts" : [
          {
            "name" : "c1",
            "class" : "http://example.org/Counter",
            "metadata" : "src/main/resources/c1_test_metadata.ttl",
            "focused-by" : [
              "body_one" // specify the body that focuses on the artifact 
            ]
          }
        ],
        "joined-by" : [ // list of bodies that are in the workspace - also possible in the agents
          "body_one"
        ]
      }
    ],
  }
}

```

**Comment by KaiTries** [comment]
This is the current standpoint:
```
{
  "http-config" : {
    ...
  },
  "notification-config" : {
    ... 
  },
  "agents" :  [
    {
      "name" : "test_agent", // unique identifier for each agent
      "agent-uri" : "http://localhost:8081", // URI of the agents WebID
      "callback-uri" : "http://localhost:8081/callback", // Endpoint for callbacks
      "body-config" : [ // list of body specifications
        {
          "metadata" : "src/main/resources/a1_body_metadata.ttl", // optional metadata for the specific body representation
          "join" : [ "w1", ] // same specification could be instantiated for multiple bodies in multiple workspaces
        },
        {
          "metadata" : "src/main/resources/a1_body_metadata.ttl", // optional metadata for the specific body representation
          // join can be omitted, first body spec without a join will be used as default representation
        }
      ]
    }
  ],
  "environment-config" : {
    "workspaces" : [
      {
        "name" : "w1",
        "metadata" : "src/main/resources/w1_test_metadata.ttl",
        "artifacts" : [
          {
            "name" : "c1",
            "class" : "http://example.org/Counter",
            "metadata" : "src/main/resources/c1_test_metadata.ttl",
            "focused-by" : [
              "agent_name" // specify the agents that focuse on the artifact 
            ]
          }
        ],
        "joined-by" : [ // list of bodies that are in the workspace, will be added at a later point just for ease of user
          "agent_name"
        ]
      }
    ],
  }
}
```
The agents will be defined outside of the environment. They are represented as a JsonArray of agent Json Objects. Each Agent will have a name and a URI that should resolve to a WebID. Optionally they can also specify a callback-uri and a body-config. 

The body-config of each agent defines the blueprints for how its bodies should be represented. It consists of an array of Json Objects. Each object defines a body through the "metadata" field. Additionally through the "join" field one can specify in which workspaces the agent should join with this specific body.

The Focus remains in the artifact and is just an array of agent names. The config will return an error if you specify an agent that is not present in the workspace.

The "joined-by" parameter in the workspace would be added at a later stage and would just enable more freedom for the user as to where he wants to specify which agents are in which workspace.

The first step is now to refactor the current functionality. I will update this issue with any progress.

**Comment by KaiTries** [comment]
Update on the expected metadata:

We will check for occurances of <> and <#someString>, these will be then filled with the URI of the hmas:ResourceProfile.

Example of an artifact called c1 being created in a workspace w1 and the following metadata is supplied:
```rdf
@prefix customArtifact: <http://www.metadata.com/>.

<#artifact> a customArtifact:CustomArtifact.
<> customArtifact:does customArtifact:SomethingVeryCool.
```

The metadata will then be added to the artifact representation as such:
```rdf
@base <http://localhost:8080/> .
@prefix hctl: <https://www.w3.org/2019/wot/hypermedia#> .
@prefix js: <https://www.w3.org/2019/wot/json-schema#> .
@prefix customArtifact: <http://www.metadata.com/> .
@prefix hmas: <https://purl.org/hmas/> .
@prefix ex: <http://example.org/> .
@prefix wotsec: <https://www.w3.org/2019/wot/security#> .
@prefix htv: <http://www.w3.org/2011/http#> .
@prefix jacamo: <https://purl.org/hmas/jacamo/> .
@prefix td: <https://www.w3.org/2019/wot/td#> .

<workspaces/w1/artifacts/c1/#artifact> a td:Thing, hmas:Artifact, ex:Counter, customArtifact:CustomArtifact;
  td:title "c1";
  td:hasSecurityConfiguration [ a wotsec:NoSecurityScheme
    ];
  td:hasActionAffordance [ a td:ActionAffordance, ex:Increment;
      td:name "inc";
      td:title "inc";
      td:hasForm [
          htv:methodName "POST";
          hctl:hasTarget <workspaces/w1/artifacts/c1/increment>;
          hctl:forContentType "application/json";
          hctl:hasOperationType td:invokeAction
        ]
    ], [ a td:ActionAffordance, jacamo:PerceiveArtifact;
      td:name "getArtifactRepresentation";
      td:hasForm [
          htv:methodName "GET";
          hctl:hasTarget <workspaces/w1/artifacts/c1>;
          hctl:forContentType "application/json";
          hctl:hasOperationType td:invokeAction
        ]
    ], [ a td:ActionAffordance, jacamo:UpdateArtifact;
      td:name "updateArtifactRepresentation";
      td:hasForm [
          htv:methodName "PUT";
          hctl:hasTarget <workspaces/w1/artifacts/c1>;
          hctl:forContentType "application/json";
          hctl:hasOperationType td:invokeAction
        ]
    ], [ a td:ActionAffordance, jacamo:DeleteArtifact;
      td:name "deleteArtifactRepresentation";
      td:hasForm [
          htv:methodName "DELETE";
          hctl:hasTarget <workspaces/w1/artifacts/c1>;
          hctl:forContentType "application/json";
          hctl:hasOperationType td:invokeAction
        ]
    ], [ a td:ActionAffordance, jacamo:Focus;
      td:name "focusArtifact";
      td:hasForm [
          htv:methodName "POST";
          hctl:hasTarget <workspaces/w1/artifacts/c1focus/>;
          hctl:forContentType "application/json";
          hctl:hasOperationType td:invokeAction
        ]
    ], [ a td:ActionAffordance, <https://purl.org/hmas/websub/subscribeToArtifact>;
      td:name "subscribeToArtifact";
      td:hasForm [
          htv:methodName "POST";
          hctl:hasTarget <hub/>;
          hctl:forContentType "application/json";
          hctl:hasOperationType td:invokeAction;
          hctl:forSubProtocol "websub"
        ];
      td:hasInputSchema [ a js:ObjectSchema;
          js:properties [ a js:StringSchema;
              js:propertyName "mode"
            ], [ a js:StringSchema;
              js:propertyName "topic"
            ], [ a js:StringSchema;
              js:propertyName "callbackIri"
            ]
        ]
    ], [ a td:ActionAffordance, <https://purl.org/hmas/websub/unsubscribeFromArtifact>;
      td:name "unsubscribeFromArtifact";
      td:hasForm [
          htv:methodName "POST";
          hctl:hasTarget <hub/>;
          hctl:forContentType "application/json";
          hctl:hasOperationType td:invokeAction;
          hctl:forSubProtocol "websub"
        ];
      td:hasInputSchema [ a js:ObjectSchema;
          js:properties [ a js:StringSchema;
              js:propertyName "mode"
            ], [ a js:StringSchema;
              js:propertyName "topic"
            ], [ a js:StringSchema;
              js:propertyName "callbackIri"
            ]
        ]
    ];
  hmas:isContainedIn <workspaces/w1/#workspace> .

<workspaces/w1/artifacts/c1> a hmas:ResourceProfile;
  hmas:isProfileOf <workspaces/w1/artifacts/c1/#artifact>;
  customArtifact:does customArtifact:SomethingVeryCool .

<workspaces/w1/#workspace> a hmas:Workspace .

```
