### ISSUE TITLE
Basic affordances not added in artifact TDs

### ISSUE THREAD

**Issue by danaivach** [Interactions-HSG/yggdrasil#60]
hMAS config: Upon registering/creating an artifact, the following signifiers are added by default in the hMAS resource profile:
- <#deleteArtifact>
- <#updateArtifact>
- <#focusArtifact> (unique to Hypermedia Artifacts)
- <#getArtifactRepresentation>,
- <#unsubscribeFromArtifact>,
- <#subscribeToArtifact>

TD config: Upon registering/creating an artifact, the following affordances are added by default in the TD:
- <#unsubscribeFromArtifact>,
- <#subscribeToArtifact>

@KaiTries, would it be a problem if you take care of aligning these sets, so that both hMAS profiles and TDs expose the same default actions descriptions?

**Comment by KaiTries** [comment]
Thanks for the report, I have added the missing action affordances to the TD representation #61
